# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 332a2057d8a70feaaa456fcf2fcccb1a5f10e192d75d88f393882179934e960406ff6928e90f2e37e7d7626cf160af25cba9ab76f788b9aebf16c678b1190a2a

test:
  secret_key_base: 1470f3f1fb4ff89cd1418f3b2d964db1d7ad2068739c04396e7430dc004d9b6139239b7a25e987fc0918eaa78985ec940fd7c763f793fd362a9dd1ac82189285

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
